export default ADD_PAGE = 'ADD_PAGE';
export default TOGGLE_ANON_STATUS = 'TOGGLE_ANON_STATUS';
export default TOGGLE_QUESTION_ORDER = 'TOGGLE_QUESTION_ORDER';
export default TOGGLE_SHOW_PAGE_NUMS = 'TOGGLE_SHOW_PAGE_NUMS';
export default TOGGLE_SHOW_PROGRESS_BAR = 'TOGGLE_SHOW_PROGRESS_BAR';
export default TOGGLE_SHOW_QUESTION_NUMS = 'TOGGLE_SHOW_QUESTION_NUMS';
export default TOGGLE_SHOW_REQUIRED_QUESTION_MARK = 'TOGGLE_SHOW_REQUIRED_QUESTION_MARK';